### ISSUE TITLE
no media links

### ISSUE THREAD

**Issue by JosefAssad** [enterprisemediawiki/MasonryMainPage#4]
Hi, I just installed this extension. The blocks weren't being rendered with any styling, so I looked in the source and could see that the relative links to the `extensions/MasonryMainPage/Masonry.css` stylesheet wasn't being loaded. This is with MW 1.24.2.

Any pointers where I might look for what's wrong?

**Comment by darenwelsh** [comment]
I'll have to spin up a VM to see if I can replicate the issue. In the meantime, can you tell me some more info? Is the javascript loading and running (i.e. the boxes move around appropriately)? Also, if you enable debug mode in MediaWiki, does it give error reports?

**Comment by JosefAssad** [comment]
I looked at the page source of [Enterprise MediaWiki](http://enterprisemediawiki.org/wiki/Enterprise_MediaWiki) and my own (apologies, it's private). What appears to be the problem is, these lines go missing:

```html
<link rel="stylesheet" media="screen" href="/w/extensions/MasonryMainPage/Masonry.css" />
```
Then much later:
```html
<script src="/w/extensions/MasonryMainPage/masonry.pkgd.min.js?303"></script>
<script src="/w/extensions/MasonryMainPage/imagesloaded.pkgd.min.js?303"></script>
<script src="/w/extensions/MasonryMainPage/masonry-common.js?303"></script>
```

So it looks like, neither the js nor the css is getting woven into the page.

None of the boxes are moving at all;  they're stacked vertically regardless of window size.

I've turned on debug, and it doesn't look like there's any relevant messages. Which is a bit odd. Here's the debug output for one pageload of a page calling 3 Masonry templates:

```
Start request GET /index.php/Forside
HTTP HEADERS:
HOST: [REDACTED]
USER-AGENT: Mozilla/5.0 (X11; Linux i686; rv:31.0) Gecko/20100101 Firefox/31.0 Iceweasel/31.7.0
ACCEPT: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
ACCEPT-LANGUAGE: en-US,en;q=0.5
ACCEPT-ENCODING: gzip, deflate
DNT: 1
COOKIE: wikiUserID=1; wikiUserName=[REDACTED]; wikiToken=[REDACTED]; wiki_session=[REDACTED]
CONNECTION: keep-alive
[caches] main: EmptyBagOStuff, message: SqlBagOStuff, parser: SqlBagOStuff
[caches] LocalisationCache: using store LCStoreDB
Connected to database 0 at localhost
Fully initialised
Title::getRestrictionTypes: applicable restrictions to [[Forside]] are {edit,move}
[ContentHandler] Created handler for wikitext: WikitextContentHandler
User: cache miss for user 1
Connected to database 0 at localhost
MessageCache::load: Loading da... got from global cache
User: loading options for user 1 from database.
User: logged in from session
User: loading options for user 1 from override cache.
Unstubbing $wgParser on call of $wgParser::firstCallInit from MessageCache::getParser
Parser: using preprocessor: Preprocessor_DOM
Unstubbing $wgLang on call of $wgLang::_unstub from ParserOptions::__construct
OutputPage::checkLastModified: client did not send If-Modified-Since header
Article::view using parser cache: yes
Article::view: doing uncached parse
Parser output marked as uncacheable.
DatabaseBase::query: Writes done: REPLACE INTO `objectcache` (keyname,value,exptime) VALUES ('X')
MessageCache::load: Loading en... got from global cache
Title::getRestrictionTypes: applicable restrictions to [[Forside]] are {edit,move}
Title::getRestrictionTypes: applicable restrictions to [[Forside]] are {edit,move}
Title::getRestrictionTypes: applicable restrictions to [[Forside]] are {edit,move}
OutputPage::sendCacheControl: no caching **
LoadBalancer::reuseConnection: this connection was not opened as a foreign connection
[runJobs] Running 1 job(s) via '/index.php?title=Special%3ARunJobs&tasks=jobs&maxjobs=1&sigexpiry=1433184810&signature=dfbb96651d70a4fa5c9ae25f8704b50931f8aed6'


Start request POST /index.php?title=Special%3ARunJobs&tasks=jobs&maxjobs=1&sigexpiry=1433184810&signature=dfbb96651d70a4fa5c9ae25f8704b50931f8aed6
HTTP HEADERS:
HOST: [REDACTED]
CONNECTION: Close
CONTENT-LENGTH: 0
[caches] main: EmptyBagOStuff, message: SqlBagOStuff, parser: SqlBagOStuff
[caches] LocalisationCache: using store LCStoreDB
Connected to database 0 at localhost
Fully initialised
IP: [REDACTED]
DatabaseBase::query: Writes done: UPDATE `page` SET page_counter = page_counter + N WHERE page_id = 'X'
DatabaseBase::query: Writes done: UPDATE `site_stats` SET ss_total_views=ss_total_views+N
Request ended normally
LoadBalancer::reuseConnection: this connection was not opened as a foreign connection
DatabaseBase::query: Writes done: UPDATE `job` SET job_token = 'X'
LoadBalancer::reuseConnection: this connection was not opened as a foreign connection
LoadBalancer::reuseConnection: this connection was not opened as a foreign connection
Connected to database 0 at localhost
[runJobs] htmlCacheUpdate Swarco pages=array(3) rootJobSignature=[REDACTED]
rootJobTimestamp=20150601112222 STARTING
DatabaseBase::query: Writes done: UPDATE `page` SET page_touched = 'X')
DatabaseBase::query: Writes done: DELETE FROM `job` WHERE job_cmd = 'X'
LoadBalancer::reuseConnection: this connection was not opened as a foreign connection
[runJobs] htmlCacheUpdate Swarco pages=array(3) rootJobSignature=[REDACTED] rootJobTimestamp=20150601112222 t=0 good
Request ended normally
```

Don't hesitate to prod for more information!

**Comment by darenwelsh** [comment]
So those four lines are not showing up in your wiki output?

Just to make sure, did you add ```require_once "$IP/extensions/MasonryMainPage/MasonryMainPage.php";``` to your LocalSettings.php?

**Comment by JosefAssad** [comment]
Yep, I can confirm that I am loading the extension from `LocalSettings.php`.

In the page source, I can see masonry css classes getting added to elements like so (copy pasted from my site's page source):

```html
<div id="mw-content-text" class="mw-content-ltr" lang="da" dir="ltr">
<div id="mediawiki-masonry-main-page-container">
<div class="item w2">
<div class="item-content">
```

Can also confirm, it's those 4 lines - the javascript and css - which are not being loaded into my rendered pages. I have a wild hunch it's pertinent to me being on a 1.24 of MW in combination with resource loading code.

**Comment by JosefAssad** [comment]
Actually, I got it working by banging on the code, changing over to using `ResourceLoader`. Would you like a pull request? php isn't my language, but in the worst case you can see what worked for me.

**Comment by JosefAssad** [comment]
Apologies for the issue comment spam. In my MW 1.24.2 [this](https://github.com/JosefAssad/MasonryMainPage/commit/6e99942d7f8958a6aa6f04c626d8e620e7b44ce9) works. I have absolutely no clue if this works in 1.23 (am guessing you stick to LTS?) which is why I'm linking you to a commit instead of submitting a pull request.

**Comment by darenwelsh** [comment]
Thank you for working on this! I will have to learn this new method and see if it still works in 1.23. We're on 1.23, but hoping to jump to 1.25 soon. It looks like we have some testing to do on other extensions first.

**Comment by darenwelsh** [comment]
I just pasted your patch onto our dev server with 1.23.2 and I get the following error:

```
Uncaught TypeError: $(...).imagesLoaded is not a function

(anonymous function) @ load.php?debug=false&lang=en&modules=site&only=scripts&skin=vector&*:1
jQuery.Callbacks.fire @ load.php?debug=false&lang=en&modules=jquery%2Cmediawiki&only=scripts&skin=vector&version=20150511T1…:12
jQuery.Callbacks.self.add @ load.php?debug=false&lang=en&modules=jquery%2Cmediawiki&only=scripts&skin=vector&version=20150511T1…:13
jQuery.fn.jQuery.ready @ load.php?debug=false&lang=en&modules=jquery%2Cmediawiki&only=scripts&skin=vector&version=20150511T1…:4
(anonymous function) @ load.php?debug=false&lang=en&modules=site&only=scripts&skin=vector&*:1
```

I will have to look into this further next week.

**Comment by JosefAssad** [comment]
I dropped a quick vanilla 1.23.2 into a spare VM; it's all rather odd. I can relate the following:

1. Seen from the outside the blocks appear to work with both your code and also with my patch in 1.23.2 (confusing!)
2. I'm not seeing those javascript errors in this vanilla 1.23.2; you're looking in the browser console, right?

I'm inclined to think we can let this one sit for a while. The reason is, it works for you and it works for me (albeit with a small workaround). And when you do upgrade to 1.25, then if it does act up in a manner resembling the original symptoms I described here then you have a candidate solution and then we can revisit this issue.

It just doesn't look like anyone else has had this issue, so unless there's a stampede to this issue it can probably safely be put on the backburner.

If on the other hand you still want to pursue it immediately, I continue to be happy to help kick ideas and debug info around. :)

**Comment by darenwelsh** [comment]
Yes, in the Chrome console. I might have compounding problems due to other extensions and the way we load some images from a second web server and wait for those to complete loading before arranging the blocks. I'll have to put this aside for now, but I hope to chase it down after I get some spare time. I appreciate your input!

**Comment by darenwelsh** [comment]
@JosefAssad - I finally got around to testing this in 1.25. Your patch works in 1.25. I still need to test it out with our existing 1.23 wiki. I may have to add in some conditional based on MW version. Can you please submit a pull request (on a different branch than master) so I can give you credit for fixing the extension for 1.24+? Thanks!

**Comment by jamesmontalvo3** [comment]
See Pull Request #5 which incorporates changes from @JosefAssad.
